apiVersion: v1
kind: Pod
metadata:
  name: result-app-pod
  labels:
    name: result-app-pod
    app: demo-voting-app
spec:
  containers:
    - name: result-app-box
      image: kodekloud/examplevotingapp_result:v1
      ports:
        # app listens on port 80
        - containerPort: 80
